### ISSUE TITLE
官方小程序html2wxml插件能否自定义自建解析服务器的请求url

### ISSUE THREAD

**Issue by martin-sun** [qwqoffice/html2wxml#11]
> 富文本的解析默认是由QwqOffice完成，存在不稳定因素，你可以自行搭建解析服务或将解析组件引入到你的项目中

问题是自建解析服务器后，官方的插件不能直接设置到自建的服务器地址。 我必须还要把你的插件在我的小程序里实现一遍，这样就很不方便。 能否为你的插件定义一个参数，可以控制解析服务器的地址？

**Comment by qwqoffice** [comment]
插件的要求有request域名，因此不能接受用户传入的参数作为请求url，建议使用组件版本
