### ISSUE TITLE
为什么不支持代码片的解析呢 没有高亮 代码格式也不对

### ISSUE THREAD

**Issue by guozimo** [qwqoffice/html2wxml#15]
<pre class="has">
<code class="language-vbscript">for (var i = 0; i &lt; oLis.length; i++) {
        oLis[i].index = i;
        oLis[i].onclick = function () {
            var _this = this;
            for (var k = 0; k &lt; oImgs.length; k++) {
                if (k != _this.index) {
                    oImgs[k].className = null;
                }
            }
            oImgs[_this.index].className = "move move" + (_this.index + 1);
        }
    }</code></pre>

**Comment by guozimo** [comment]
能否支持一下代码的高亮和格式呢 
微信号：gwd1991

**Comment by qwqoffice** [comment]
经测试没有问题
![image](https://user-images.githubusercontent.com/18651085/55292376-b2f92280-541c-11e9-8250-85f19355bb53.png)
