### ISSUE TITLE
请求https://www.qwqoffice.com/html2wxml/ 返回的数据模拟器和真机不一致

### ISSUE THREAD

**Issue by guozimo** [qwqoffice/html2wxml#16]
swan.request({
                        url: 'https://www.qwqoffice.com/html2wxml/',
                        data: data,
                        method: 'POST',
                        header: {
                            'content-type': 'application/x-www-form-urlencoded'
                        },
返回的数据 模拟器和真机不一致   真机器 返回的代码片数据 是 text 
数据是下面
<pre class="has">
<code class="language-vbscript">for (var i = 0; i &lt; oLis.length; i++) {
        oLis[i].index = i;
        oLis[i].onclick = function () {
            var _this = this;
            for (var k = 0; k &lt; oImgs.length; k++) {
                if (k != _this.index) {
                    oImgs[k].className = null;
                }
            }
            oImgs[_this.index].className = "move move" + (_this.index + 1);
        }
    }</code></pre>

请尽快解决一下

**Comment by qwqoffice** [comment]
请提供请求的data
