### ISSUE TITLE
对语言标签的兼容问题

### ISSUE THREAD

**Issue by maojindao55** [qwqoffice/html2wxml#17]
<pre><?php echo 12321; ?></pre>
这样传入内容无法解析

<pre>echo 12321; </pre>
这样解析正常

对<?php标签不兼容吗？

**Comment by qwqoffice** [comment]
请使用html实体字符
例如`<htmltowxml text="<pre>&lt;?php echo 'asd'</pre>" bindWxmlTagATap="wxmlTagATap" />`
