### ISSUE TITLE
Some selectors are not allowed in component wxss

### ISSUE THREAD

**Issue by yrx0823** [qwqoffice/html2wxml#22]
![image](https://user-images.githubusercontent.com/23035615/57205301-6642d180-6ff0-11e9-91e6-850be07a4e9e.png)

**Comment by yrx0823** [comment]
1.4.0版本报错

**Comment by sav7ng** [comment]
感觉还是建议退回到1.3.1版本用。

**Comment by qwqoffice** [comment]
并非错误 可忽略
1.3.1版本将在5月15日停止使用 请知悉

**Comment by sav7ng** [comment]
那我得升级了~
