### ISSUE TITLE
部分代码渲染失败

### ISSUE THREAD

**Issue by baichen99** [qwqoffice/html2wxml#23]
在pre标签中<>中的内容不会渲染出来

[详细代码](https://github.com/baichen99/my_issue)

![](https://s2.ax1x.com/2019/05/09/EctyjO.png)

**Comment by qwqoffice** [comment]
请使用字符实体`&lt;`和`&gt;`来代替`<`和`>`
详见HTML实体：http://www.w3school.com.cn/html/html_entities.asp

**Comment by baichen99** [comment]
问题已解决  感谢回复
