### ISSUE TITLE
https://github.com/qwqoffice/html2wxml实例总是提示更改app.json中的版本号，更改后依然提示更改app.json版本号

### ISSUE THREAD

**Issue by sunning2** [qwqoffice/html2wxml#28]

**Comment by sunning2** [comment]
![image](https://user-images.githubusercontent.com/37064838/82531870-bf859080-9b72-11ea-9a9f-7b872db479a9.png)

**Comment by qwqoffice** [comment]
请使用插件版，或将组件版api地址改为https://html2wxml.qwqoffice.com/api/

**Comment by sunning2** [comment]
请问是修改componets目录下的还是index.js里面的

**Comment by qwqoffice** [comment]
全局搜索qwqoffice.com

**Comment by sunning2** [comment]
请问是https://www.qwqoffice.com/html2wxml/example.html修改成https://html2wxml.qwqoffice.com/api/吗？

**Comment by qwqoffice** [comment]
你现在用的是插件版还是组件版

**Comment by sunning2** [comment]
组件版

**Comment by qwqoffice** [comment]
https://www.qwqoffice.com/html2wxml/ -> https://html2wxml.qwqoffice.com/api/

**Comment by qwqoffice** [comment]
或直接使用仓库中html2wxml-component

**Comment by sunning2** [comment]
嗯嗯，问题已解决，十分感谢
