### ISSUE TITLE
请问如何支持腾讯视频？

### ISSUE THREAD

**Issue by yzqiang** [qwqoffice/html2wxml#3]
腾讯视频的小程序插件虽然好用，但是还是希望在文章对应位置显示视频，类似您 Demo 中的效果。
但是腾讯视频的解析插件 smartideo 只能生成 iframe 结构的视频播放，可以支持 H5 ，但是不支持微信小程序。
现在的情况是，我可以获取到腾讯视频的 vid ，有没有可能通过微信小程序的 video 标签来显示腾讯视频？
谢谢！

**Comment by yzqiang** [comment]
我试了一下，如果把 iframe 里面的 video 标签抠出来，用您的代码是可以播放的。
![image](https://user-images.githubusercontent.com/1594490/45265417-128de180-b47d-11e8-9ee8-1690a191b07f.png)
这样的话，关键问题就是如何获取 video 标签了。

**Comment by qwqoffice** [comment]
暂不支持腾讯视频，只支持可直接播放的视频链接

**Comment by yzqiang** [comment]
我写了一段服务器端的代码，将腾讯视频的video标签抠出来后就可以播放了，效果很赞。

**Comment by self-transition** [comment]
您好，遇到了同样的问题，可以讲讲实现细节吗？

**Comment by self-transition** [comment]
我也是拿到了腾讯视频的 vid，将iframe内嵌的视屏url却无法播放，请问怎样可以播放呢

**Comment by qwqoffice** [comment]
可使用官方腾讯视频组件
