### ISSUE TITLE
使用过程中出现 wxml11 not found 错误

### ISSUE THREAD

**Issue by yzqiang** [qwqoffice/html2wxml#5]
这是一段秀米的格式文本，内容比较复杂：
[xiumi.txt](https://github.com/qwqoffice/html2wxml/files/2467645/xiumi.txt)
处理后出现错误提示，但是显示效果没有发现问题。
下面是微信开发者工具中的错误提示：
![image](https://user-images.githubusercontent.com/1594490/46785270-dc859b00-cd63-11e8-8bd2-d01def06959c.png)

**Comment by qwqoffice** [comment]
请自行添加模板嵌套
