### ISSUE TITLE
建议加入对外部样式的支持

### ISSUE THREAD

**Issue by yzqiang** [qwqoffice/html2wxml#8]
可以在组件模式下，在 html2wxml.js 中加入如下代码：
```
externalClasses: ['external-class'],
```
这样就可以在组件外部设置组件内部的样式了。

**Comment by qwqoffice** [comment]
已添加`addGlobalClass` https://github.com/qwqoffice/html2wxml/commit/2f1435d08267ef634e1b88c1338a4fc8842d350a
外部样式类对覆盖组件内样式作用不大，使用`addGlobalClass` 代替（基础库2.2.3或以上）
